# GitLeaks configuration for Supabase Configurator
title = "Supabase Configurator GitLeaks Config"

# Extend default rules with allowlists for template generation files
[extend]
useDefault = true

# Global allowlist for files containing template patterns
[allowlist]
description = "Allow template generation files with example secrets"
commits = ["ALL"]
paths = [
    # Template and generator files
    '''workers/modules/generators\.mjs''',
    '''workers/modules/templates\.mjs''',
    '''workers/modules/utils\.mjs''',
    # Backup and legacy files  
    '''workers/index-old\.mjs''',
    '''workers/index\.backup\..*''',
    '''workers/index\.legacy\..*''',
    '''.*backup.*''',
    '''.*legacy.*''',
    '''.*old\..*''',
    # Configuration templates
    '''.*\.template$''',
    '''.*docker-compose.*\.yml$''',
    '''.*\.env\.example$''',
]