version: '3.8'

services:
  app:
    build: .
    container_name: supabase-configurator
    restart: unless-stopped
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
      - ./app/templates:/app/app/templates:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:size=100M
    user: "1000:1000"
    cap_drop:
      - ALL
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: supabase-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/supabase-configurator.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/ssl/certs:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  logs:
